// <auto-generated />
namespace JobPortal.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateidentitymodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateidentitymodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202011071139312_update identity model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
